### ISSUE TITLE
Fix SQL syntax error in login.php

### ISSUE THREAD

**Issue by vishwajeetsharma** [pratham-jaiswal/HotelBookingManagement#2]
I encountered a fatal SQL syntax error while using the login functionality in the `login.php` file. The error occurs due to the incorrect usage of prepared statements when querying the database. Specifically, the prepared statement lacks a bound parameter for the username.

To fix this issue, I've modified the code to properly bind the username parameter before executing the SQL query.

**Error message**

> Fatal error: Uncaught mysqli_sql_exception: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '?' at line 1 in C:\xampp\htdocs\HotelBookingManagement\login.php:29 Stack trace: #0 C:\xampp\htdocs\HotelBookingManagement\login.php(29): mysqli_query(Object(mysqli), 'SELECT id, fnam...') # 1 {main} thrown in C:\xampp\htdocs\HotelBookingManagement\login.php on line 29

**Steps to Reproduce:**
1. Navigate to the login page.
2. Attempt to login with valid credentials.

**Expected Behavior:**
The user should be logged in successfully without encountering any errors.

**Actual Behavior:**
A fatal SQL syntax error is thrown, preventing successful login.

**Proposed Solution:**
I have addressed the issue by modifying the code in `login.php` to properly bind the username parameter before executing the SQL query. This should resolve the SQL syntax error and allow users to login without any issues.

Please review and merge the proposed changes.

**Comment by pratham-jaiswal** [comment]
Hey, thanks for pointing out the issue and fixing it!
